### ISSUE TITLE
Carousel: Cannot find module "process" from "/@ebay/ebayui-core$1.0.2/dist/components/ebay-icon"

### ISSUE THREAD

**Issue by sraone** [eBay/ebayui-core#409]
# Bug Report

After migrating to 1.0.2, I am getting an error `Uncaught Error: Cannot find module "process" from "/@ebay/ebayui-core$1.0.2/dist/components/ebay-icon"` due this carousel is not showing next and previous buttons.

## Screenshots

![image](https://user-images.githubusercontent.com/1853563/45453148-d59c3780-b694-11e8-8b34-39e2ff4b7ebe.png)

![image](https://user-images.githubusercontent.com/1853563/45453181-ee0c5200-b694-11e8-9ac5-552c6db4dd17.png)

**Comment by seangates** [comment]
@sraone What version of Marko and Marko Widgets are you running?

**Comment by sraone** [comment]
@seangates marko@3.14.3 and marko-widgets@6.6

**Comment by sraone** [comment]
@msendlakowski I found very interesting things while debugging.
I found that `process` is not registered in `global` scope in my application because it's not registered as `built-in` module by `lasso-require`. But when tried testing the component in the new sample application, `process` module is available in global scope and `ebay-icon` is working as expected. I compared `lasso-modules-meta` file from both application and interestingly `process` is registered as `built-in` module in the sample application and it's not `built-in` in my application.

My application `lasso-modules-meta`
![image](https://user-images.githubusercontent.com/1853563/45579196-e686ad80-b83a-11e8-98a3-135d798e61b8.png)

Sample application `lasso-modules-meta`
![image](https://user-images.githubusercontent.com/1853563/45579209-fc946e00-b83a-11e8-9498-d1e85b14ce2c.png)

After debugging further down, I see there is a bug in `lasso-require` module to identify the `built-in` modules when the application has multiple versions of `process` dependencies.

In my application, there are two different versions of `process` dependencies 

![image](https://user-images.githubusercontent.com/1853563/45579340-cc010400-b83b-11e8-84a8-3a645105f086.png)

If I remove `process@0.11.10`, the component is working as expected.

**Comment by msendlakowski** [comment]
@DylanPiercey @mlrawlings  This seems like more of a lasso issue.  Can you provide guidance?

**Comment by DylanPiercey** [comment]
@sraone do you know why you have two `process` dependencies? (`yarn list process`)
Either way I'll take a look.

**Comment by DylanPiercey** [comment]
Thinking on this more, you really shouldn't ever be sending down two versions of any builtin shim (`process` in this case). I am still curious why you have two `process` dependencies especially a direct dependency? You should never have to manually include any of the browser shims yourself.

If you need the latest version of the `process` shim I'd recommend updating Lasso to v3.

**Comment by seangates** [comment]
Looks like `marko-widgets-playground` (via `browser-refresh` and `browserify`) might be the culprit:

```
LM-SJC-11005201:[redacted] sgates$ yarn why process
yarn why v1.9.4
[1/4] 🤔  Why do we have the module "process"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "process@0.11.10"
info Has been hoisted to "process"
info Reasons this module exists
   - Hoisted from "marko-widgets-playground#browser-refresh#browserify#process"
   - Hoisted from "marko-widgets-playground#browser-refresh#browserify#insert-module-globals#process"
   - Hoisted from "marko-widgets-playground#browser-refresh#browserify#timers-browserify#process"
=> Found "lasso-require#process@0.6.0"
info This module exists because "lasso-require" depends on it.
```

**Comment by seangates** [comment]
Ignore my (now deleted) previous comment.

**Comment by sraone** [comment]
@DylanPiercey `process` is not a direct dependency but there is another module in an app which is using the different version of 'process`.

![image](https://user-images.githubusercontent.com/1853563/45639236-4ad88580-ba64-11e8-9813-7d6d5491d025.png)
![image](https://user-images.githubusercontent.com/1853563/45639251-575cde00-ba64-11e8-81ff-3977cad2b00d.png)

`yarn` list

![image](https://user-images.githubusercontent.com/1853563/45639640-6f812d00-ba65-11e8-8317-d94977de1cd4.png)

**Comment by DylanPiercey** [comment]
@sraone gotcha. Maybe we should support this then.

**Comment by sraone** [comment]
@DylanPiercey Is there any plan for fixing this issue in coming releases?

**Comment by ianmcburnie** [comment]
@sraone Is this a blocker or do you currently have a workaround in place? We are trying to prioritize and schedule these carousel related issues for our upcoming patch, minor and major releases.

**Comment by DylanPiercey** [comment]
@sraone I released a new version of `lasso-require` which updates it's dependencies which should resolve this issue. If you upgrade the dependencies that rely on `lasso-require` then you should be good 😃.
